# Generated by Django 6.1 on 2026-08-27 10:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='make',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='model',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('car', 'Car'), ('bike', 'Bike'), ('truck', 'Truck'), ('van', 'Van')], default='car', max_length=10),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='year',
            field=models.PositiveIntegerField(default=2020),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='registration_no',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='registration_no must match format: MH12AB1234', regex='^[A-Z]{2}[0-9]{2}[A-Z]{1,2}[0-9]{4}$')]),
        ),
    ]
