# Generated by Django 6.1 on 2026-08-27 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0002_vehicle_is_active_vehicle_make_vehicle_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='body_type',
            field=models.CharField(choices=[('sedan', 'Sedan'), ('suv', 'SUV'), ('hatchback', 'Hatchback'), ('coupe', 'Coupe'), ('convertible', 'Convertible'), ('pickup', 'Pickup'), ('minivan', 'Minivan'), ('not_applicable', 'Not Applicable')], default='sedan', max_length=20),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='color',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='engine_capacity_cc',
            field=models.PositiveIntegerField(default=1200),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='fuel_type',
            field=models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('electric', 'Electric'), ('hybrid', 'Hybrid'), ('cng', 'CNG')], default='petrol', max_length=10),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='insurance_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='last_service_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='seating_capacity',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='transmission_type',
            field=models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatic')], default='manual', max_length=10),
        ),
    ]
