# Generated by Django 6.1 on 2026-08-27 10:18

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistitem',
            name='category',
            field=models.CharField(blank=True, choices=[('exterior', 'Exterior'), ('interior', 'Interior'), ('mechanical', 'Mechanical'), ('electrical', 'Electrical')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='severity',
            field=models.CharField(blank=True, choices=[('minor', 'Minor'), ('moderate', 'Moderate'), ('severe', 'Severe')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 8, 27, 10, 18, 44, 524976, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inspection',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_inspections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inspection',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
